version: 2
defaults:
  working_directory: ~/repo
jobs:
  build:
    docker:
      - image: circleci/node:10.11
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          name: Restoring cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install node_modules
          command: 'sudo npm install'
  test:
    docker:
      - image: circleci/node:10.11
    steps:
      - run:
         name: Run test-dev
         command: 'sudo npm run test:dev'
      - store_artifacts:
          path: /testresult

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build