version: 2
defaults:
  working_directory: ~/repo
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          name: Restoring cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install node_modules
          command: 'sudo npm install'
      - persist_to_workspace:
          root: ./
          paths:
            - .
  test:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Run test-dev
          command: 'sudo npm run test:dev'
        
workflows:
  version: 2
  build_and_test_dev:
    jobs:
      - build
      - test:
          requires:
            - build